version: "3.9"

services:
  db:
    image: postgres:15
    container_name: desafio2_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: desafio
    volumes:
      - desafio2_pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5433:5432"

volumes:
  desafio2_pgdata: