version: '3.9'

services:
  servidor_web:
    build: ./Server
    container_name: servidor_web
    ports:
      - "8080:8080"
    networks:
      - minha_rede

  cliente:
    build: ./Client
    container_name: cliente
    depends_on:
      - servidor_web
    networks:
      - minha_rede

networks:
  minha_rede:
    driver: bridge