version: "3.9"

services:
  service_users:
    build: ./service_users
    container_name: desafio5_users
    ports:
      - "5001:5001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 5s
      timeout: 2s
      retries: 5

  service_orders:
    build: ./service_orders
    container_name: desafio5_orders
    ports:
      - "5002:5002"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 5s
      timeout: 2s
      retries: 5

  gateway:
    build: ./gateway
    container_name: desafio5_gateway
    ports:
      - "5000:5000"
    environment:
      USERS_URL: http://service_users:5001/users
      ORDERS_URL: http://service_orders:5002/orders
    depends_on:
      service_users:
        condition: service_healthy
      service_orders:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 5s
      timeout: 2s
      retries: 5